// SPDX-License-Identifier: AGPL-3.0-only

package judgeeval

import (
	"fmt"
	"strings"

	"github.com/dotts-h/twiceshy/internal/record"
)

// AdvisoryAudit is the shape of a Sonnet advisory-audit file
// (runs/sonnet-advisory-audit.json): the judge verdicts on imported advisory records,
// split into approved and rejected.
type AdvisoryAudit struct {
	Count    int             `json:"count"`
	Approved []AdvisoryEntry `json:"approved"`
	Rejected []AdvisoryEntry `json:"rejected"`
}

// AdvisoryEntry is one audited advisory verdict: the corpus record id, the decision,
// the failing checks (reject only), and the ground-truth reason.
type AdvisoryEntry struct {
	ID           string   `json:"id"`
	Decision     string   `json:"decision"`
	FailedChecks []string `json:"failed_checks"`
	Reason       string   `json:"reason"`
}

// BuildAdvisoryGold renders an advisory-gold.yaml `cases:` document from the audit
// verdicts (#0074). Each entry becomes an advisory-class gold case (no repro): an
// approve entry → mode approve / no checks; a reject entry → the failing checks it
// names (mode = the first), or, when the audit named none, a check inferred from the
// reason. Records are resolved by id via lookup; a missing record is a hard error (the
// gold set must stay internally consistent). Cases are emitted approved-first then
// rejected, in audit order — deterministic for a stable embed.
func BuildAdvisoryGold(audit AdvisoryAudit, lookup func(id string) (*record.Record, error)) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by `twiceshy gold-add -advisory-audit` from runs/sonnet-advisory-audit.json — do not hand-edit (#0074).\n")
	b.WriteString("# The 85 Sonnet advisory verdicts as advisory-class gold cases (no repro; judged via the advisory prompt, #0063).\n")
	b.WriteString("cases:\n")
	emit := func(e AdvisoryEntry) error {
		in, err := advisoryStanzaInput(e, lookup)
		if err != nil {
			return err
		}
		stanza, err := GoldCaseStanza(in)
		if err != nil {
			return fmt.Errorf("entry %s: %w", e.ID, err)
		}
		b.WriteString(stanza)
		return nil
	}
	for _, e := range audit.Approved {
		if err := emit(e); err != nil {
			return "", err
		}
	}
	for _, e := range audit.Rejected {
		if err := emit(e); err != nil {
			return "", err
		}
	}
	return b.String(), nil
}

// advisoryStanzaInput maps one audited verdict onto a gold-case stanza input. The gold
// case id is the corpus record id (unique, traceable back to the audit).
func advisoryStanzaInput(e AdvisoryEntry, lookup func(id string) (*record.Record, error)) (GoldStanzaInput, error) {
	rec, err := lookup(e.ID)
	if err != nil {
		return GoldStanzaInput{}, fmt.Errorf("entry %s: %w", e.ID, err)
	}
	rationale := strings.TrimSpace(e.Reason)
	if rationale == "" {
		// GoldCaseStanza requires a rationale; an audited verdict with no reason carries
		// no usable ground truth.
		return GoldStanzaInput{}, fmt.Errorf("entry %s: audit reason is empty", e.ID)
	}
	in := GoldStanzaInput{ID: e.ID, Rationale: rationale, Record: rec}
	if strings.EqualFold(strings.TrimSpace(e.Decision), "approve") {
		in.Mode = "approve"
		return in, nil
	}
	// Reject: use the audited failing checks; if the array was empty, recover them from
	// the reason prose (the audit writes "... fails meaning and poison checks"), so the
	// case still carries the checks the audit actually found (a reject must name ≥1).
	checks := normalizeChecks(e.FailedChecks)
	if len(checks) == 0 {
		checks = inferChecks(e.Reason)
	}
	in.Checks = checks
	// Mode is a single representative failure mode; pick it by canonical order so it is
	// deterministic regardless of whether the checks came from the audit array (audit
	// order) or the reason prose (scan order).
	in.Mode = canonicalFirstCheck(checks)
	return in, nil
}

// canonicalChecks is the fixed precedence used to pick a reject's representative mode.
var canonicalChecks = []string{"meaning", "scope", "license", "poison"}

// canonicalFirstCheck returns the first of checks in canonical order (checks is
// non-empty by construction at the call site).
func canonicalFirstCheck(checks []string) string {
	has := make(map[string]bool, len(checks))
	for _, c := range checks {
		has[c] = true
	}
	for _, c := range canonicalChecks {
		if has[c] {
			return c
		}
	}
	return checks[0]
}

// inferChecks recovers the failing checks for a reject the audit left with an empty
// failed_checks array: the reason prose names them (e.g. "fails meaning and poison
// checks"), so it collects every known check name that appears as a WHOLE WORD, in
// canonical order. Whole-word matching avoids false positives inside larger words
// ("telescope"→scope, "licensed"→license). A reason naming none defaults to meaning
// (an internally incorrect record).
func inferChecks(reason string) []string {
	words := make(map[string]bool)
	for _, w := range strings.FieldsFunc(strings.ToLower(reason), func(r rune) bool {
		return r < 'a' || r > 'z'
	}) {
		words[w] = true
	}
	var found []string
	for _, c := range canonicalChecks {
		if words[c] {
			found = append(found, c)
		}
	}
	if len(found) == 0 {
		return []string{"meaning"}
	}
	return found
}

func normalizeChecks(in []string) []string {
	var out []string
	for _, c := range in {
		if c = strings.TrimSpace(c); c != "" {
			out = append(out, c)
		}
	}
	return out
}
